In [2]:
import numpy as np

b = np.random.rand(4,8,4)

print(b)

idx = np.arange(8)
idx_new = np.reshape(idx,(2,4))
idx_new = np.reshape(idx_new.T,(-1))
print(idx_new)

b = np.reshape(b,(4,4,8))
b = b[:,:,idx_new]
print(b)


[[[0.84027421 0.32235579 0.44319704 0.58678421]
  [0.51387967 0.0768735  0.00449425 0.8179171 ]
  [0.06500548 0.48396934 0.50555961 0.96443365]
  [0.49637688 0.38881075 0.99326374 0.25627054]
  [0.76745504 0.86221709 0.8541169  0.03701721]
  [0.77812127 0.01199394 0.45298482 0.34743229]
  [0.12237584 0.08212498 0.31381107 0.18484515]
  [0.43812376 0.37516627 0.95931759 0.72586869]]

 [[0.779753   0.27172649 0.68911439 0.61557413]
  [0.91221597 0.06142268 0.62816489 0.40642082]
  [0.39137435 0.68176608 0.26230065 0.95688786]
  [0.27224408 0.92877378 0.14081026 0.41061384]
  [0.64645114 0.87423337 0.646656   0.54635137]
  [0.15749854 0.49051851 0.12290007 0.79790327]
  [0.84916815 0.01066635 0.04964238 0.7514341 ]
  [0.47681907 0.74428723 0.29945757 0.16740416]]

 [[0.1352531  0.41441796 0.13437577 0.16941663]
  [0.65261908 0.39278088 0.08145474 0.20981816]
  [0.28338705 0.10502121 0.45391349 0.25486953]
  [0.39102645 0.78641878 0.1662179  0.15499858]
  [0.83198776 0.48378792 0.20994525 

In [6]:
a = np.ones((3,3))
x = np.array([1,2,3])
a[(1,2),(2,2)] = [2,2]
print(a)

[[1. 1. 1.]
 [1. 1. 2.]
 [1. 1. 2.]]


In [53]:
len(x)

5

In [16]:
import pickle
import gzip
with open('data.pkl', 'rb') as f:
    u = pickle._Unpickler(f)
    u.encoding = 'latin1'
    p = u.load()

In [21]:
data = p[0]
target = p[1]
N,D = data.shape
training_per = 0.7
training_len = int(training_per*N)

train_data = data[:training_len]
train_tar  = target[:training_len]
test_data  = data[training_len:]
test_tar   = target[training_len:]

In [23]:
f = gzip.open('t10k-images-idx3-ubyte.gz', 'rb')

In [31]:
from mnist import MNIST

mndata = MNIST('samples')

images, labels = mndata.load_training()
# or
images, labels = mndata.load_testing()

In [41]:
a = np.asarray(images)


In [42]:
a.shape

(60000, 784)